export enum EVerificationResponseStatus {
    SUCCESSFUL = 'SUCCESSFUL',
    INCORRECT_VERIFICATION_CODE = 'INCORRECT_VERIFICATION_CODE',
    INVALID_PARAMS = 'INVALID_PARAMS',
    EXTERNAL_ERROR = 'EXTERNAL_ERROR',
    UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
}
